### ISSUE TITLE
The API is broken asf

### ISSUE THREAD

**Issue by HyScript7** [ProjNull/Praeteritum#9]
Hark, noble comrades of our endeavor. Within this missive lies the litany of errors we have encountered within the labyrinthine corridors of our API router and attendant services. Behold, I shall unveil the entirety of the stack trace, encompassing even the chronicles of our requests, and delineate the rites necessary to summon forth each error anew. Let none be so bold as to seal this tome until all the pathways of our API stand rectified and proven by trial.

Here's the first one
```
INFO:     172.19.0.6:60502 - "POST /api/v1/groups/create_group HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastapi/encoders.py", line 324, in jsonable_encoder
    data = dict(obj)
           ^^^^^^^^^
TypeError: 'coroutine' object is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastapi/encoders.py", line 329, in jsonable_encoder
    data = vars(obj)
           ^^^^^^^^^
TypeError: vars() argument must have __dict__ attribute
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 180, in serialize_response
    return jsonable_encoder(response_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/encoders.py", line 332, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'coroutine' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

Steps to reproduce:
- Authenticate on swagger
- Send a request to /api/v1/groups/create_group with default values

**Comment by HyScript7** [comment]
@SomeKristi There is an issue with what apears to be the permission lookup.
Stacktrace:
```
praeteritum-backend-1   | 2024-06-03 12:00:46,754 INFO sqlalchemy.engine.Engine BEGIN (implicit)
praeteritum-backend-1   | 2024-06-03 12:00:46,754 INFO sqlalchemy.engine.Engine SELECT user_to_group.utg_id AS user_to_group_utg_id, user_to_group.permissions AS user_to_group_permissions, user_to_group.user_id AS user_to_group_user_id, user_to_group.group_id AS user_to_group_group_id 
praeteritum-backend-1   | FROM user_to_group 
praeteritum-backend-1   | WHERE user_to_group.user_id = ?
praeteritum-backend-1   |  LIMIT ? OFFSET ?
praeteritum-backend-1   | 2024-06-03 12:00:46,754 INFO sqlalchemy.engine.Engine [cached since 46.25s ago] ('string', 1, 0)
praeteritum-backend-1   | 2024-06-03 12:00:46,758 INFO sqlalchemy.engine.Engine ROLLBACK
praeteritum-backend-1   | INFO:     172.22.0.6:56608 - "DELETE /api/v1/groups/delete_group HTTP/1.0" 500 Internal Server Error
praeteritum-ingress-1   | 192.168.65.1 - - [03/Jun/2024:12:00:46 +0000] "DELETE /api/v1/groups/delete_group HTTP/1.1" 500 21 "http://127.0.0.1/docs" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0"
praeteritum-backend-1   | ERROR:    Exception in ASGI application
praeteritum-backend-1   | Traceback (most recent call last):
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
praeteritum-backend-1   |     result = await app(  # type: ignore[func-returns-value]
praeteritum-backend-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
praeteritum-backend-1   |     return await self.app(scope, receive, send)
praeteritum-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
praeteritum-backend-1   |     await super().__call__(scope, receive, send)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
praeteritum-backend-1   |     await self.middleware_stack(scope, receive, send)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
praeteritum-backend-1   |     raise exc
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
praeteritum-backend-1   |     await self.app(scope, receive, _send)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
praeteritum-backend-1   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
praeteritum-backend-1   |     raise exc
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
praeteritum-backend-1   |     await app(scope, receive, sender)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
praeteritum-backend-1   |     await self.middleware_stack(scope, receive, send)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
praeteritum-backend-1   |     await route.handle(scope, receive, send)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
praeteritum-backend-1   |     await self.app(scope, receive, send)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
praeteritum-backend-1   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
praeteritum-backend-1   |     raise exc
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
praeteritum-backend-1   |     await app(scope, receive, sender)
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
praeteritum-backend-1   |     response = await func(request)
praeteritum-backend-1   |                ^^^^^^^^^^^^^^^^^^^
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
praeteritum-backend-1   |     raw_response = await run_endpoint_function(
praeteritum-backend-1   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
praeteritum-backend-1   |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
praeteritum-backend-1   |     return await dependant.call(**values)
praeteritum-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
praeteritum-backend-1   |   File "/opt/prae-be/app/routes/v1/groups.py", line 30, in delete_group
praeteritum-backend-1   |     return await group_service.delete_group(db, body)
praeteritum-backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
praeteritum-backend-1   |   File "/opt/prae-be/app/database/services/group_service.py", line 40, in delete_group
praeteritum-backend-1   |     if db.query(UserToGroup).filter(UserToGroup.user_id==query.user_id and UserToGroup.group_id==query.group_id).first().permissions == 4:
praeteritum-backend-1   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
praeteritum-backend-1   | AttributeError: 'NoneType' object has no attribute 'permissions'
```

Steps to reproduce:
- Sign in
- Create group (Do not assign your self as owner)
- Attempt to delete it

This won't be solved by simply making the creator the owner, as anyone attempting this would trigger this exception.

**Comment by HyScript7** [comment]
Since everyone is kind of working on this rn, I'll just close it lol
